site_name: <<Pipeline Name>>
repo_url: https://github.com/JoelPaullONS/docs_workshop
repo_name: JoelPaullONS/docs_workshop

nav:
  - Home: index.md
  - About: about.md
  - Data: data.md
  - Functionality: functionality.md
  - Usage Notes: usage.md
  - Development Notes: dev_notes.md

theme: mkdocs

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid@10.4.0/dist/mermaid.esm.min.mjs

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid2
          class: mermaid2
          format: !!python/name:mermaid2.fence_mermaid
